# docker build . -t cenzwong/fastapi-helloworld:latest
# docker push cenzwong/fastapi-helloworld:latest
# docker run cenzwong/fastapi-helloworld:latest -p 80:80

# set base image (host OS)
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY ./app /app
